[package]
name = "iris"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
# theia
bifrost = { git = "https://github.com/theia-hq/bifrost" }
bifrost-iroh = { git = "https://github.com/theia-hq/bifrost" }
bifrost-wire = { git = "https://github.com/theia-hq/bifrost" }

clap = { version = "4", features = ["derive", "env"] }
eyre = "0.6"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
indicatif = "0.17"
rand = "0.8"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
# theia
bifrost-mem = { git = "https://github.com/theia-hq/bifrost" }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
wildcard_imports = "deny"
std_instead_of_core = "warn"

[lints.rust]
unused_must_use = "deny"
